# Generated by Django 4.1.3 on 2023-02-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
