# Generated by Django 4.1.3 on 2023-03-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creator_username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
