# Generated by Django 4.1.3 on 2023-03-24 19:00

from django.db import migrations, models
import quickstart.models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/media/images/default.png', null=True, upload_to=quickstart.models.upload_to),
        ),
    ]
