# Generated by Django 4.1.3 on 2023-04-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_customuser_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reported',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
