# Generated by Django 4.1.3 on 2023-04-03 16:12

from django.db import migrations, models
import quickstart.models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_post_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/images/default.png', null=True, upload_to=quickstart.models.upload_to),
        ),
    ]
