# Generated by Django 4.1.3 on 2023-09-06 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_alter_customuser_profile_picture_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 15, 44, 49, 544541, tzinfo=datetime.timezone.utc)),
        ),
    ]
