# Generated by Django 4.1.3 on 2023-10-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_alter_story_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='inappropriate_post_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
