# Generated by Django 4.1.3 on 2023-10-10 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_customuser_inappropriate_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, related_name='requested_to_follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
