# Generated by Django 4.1.3 on 2023-10-11 13:48

from django.db import migrations, models
import quickstart.models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_customuser_follow_requests_customuser_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/images/default.png', null=True, upload_to=quickstart.models.upload_to),
        ),
    ]
